### ISSUE TITLE
Can't click anything on the d.gg/bigscreen after mousewheel clicking on chat

### ISSUE THREAD

**Issue by royalred01** [destinygg/website#92] opened 2015-08-14 23:39 UTC
Sometimes i mousewheel click on the chat and drag up or down to scroll through the chat quickly but after doing that i can't click anything on the website and to solve the problem i can't refresh the page i need to close the tab and re-open it.  I can't click links in chat, any of the icons at the top of the page (Blog, Twitter, Youtube etc.) and i can't pause the stream or change the volume.

This isn't a big deal but i feel it's better to post about it since i found this bug reporting part of the website.

The browser i use is Chrome.

**Comment by sztanpet** [comment] 2015-08-31 08:38
duplicate of #58 
please search before making issues

**Closed by sztanpet** 2015-08-31 08:38 UTC
