### ISSUE TITLE
middle-clicking in chat breaks the left click on all elements in chrome

### ISSUE THREAD

**Issue by MammothJerk** [destinygg/website#99] opened 2015-09-22 03:54 UTC
when middle-clicking in chat to scroll (up,down,left,right), if you move left or right the cursor icon will get stuck as the arrow pointing in the direction you move and stop responding to left-clicks. 
you cannot left-click anything on the page i.e you cannot pause the stream, cant click anything in the banner, cannot focus the message box.

you have to close and then reopen the tab for it to fix itself, reloading like normal doesnt help.

In other browsers i can ONLY scroll up/down so it appears to have something to do with the chrome browser

Google chrome
Version 46.0.2490.33 beta-m (64-bit)

tried with all extensions disabled and in incognito mode.

**Comment by sztanpet** [comment] 2015-09-22 06:04
duplicate of #58 
please search the issues before submitting new ones

**Closed by sztanpet** 2015-09-22 06:04 UTC
